export const ADD_BOOK_START = "ADD_BOOK_START";
export const ADD_BOOK_SUCCESS = "ADD_BOOK_SUCCESS";
export const ADD_BOOK_FAIL = "ADD_BOOK_FAIL";

export const REMOVE_BOOK = "REMOVE_BOOK";
export const DELETE_BOOK_SUCCESS = "DELETE_BOOK_SUCCESS";
export const REMOVE_BOOK_FAIL = "REMOVE_BOOK_FAIL";

export const SET_BOOKS_START = "SET_BOOKS_START";
export const SET_BOOKS = "SET_BOOKS";
export const FETCH_BOOKS_FAILED = "FETCH_BOOKS_FAILED";

export const DISPLAY_BOOK = "DISPLAY_BOOK";
export const HIDE_BOOK = "HIDE_BOOK";

export const DISPLAY_ADD_BOOK = "DISPLAY_ADD_BOOK";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_DISPLAY = "AUTH_DISPLAY";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const CHOOSE_SORT_METHOD = "CHOOSE_SORT_METHOD";
export const CHOOSE_BOOK_TYPE = "CHOOSE_BOOK_TYPE";
export const ENTER_SEARCH_FIELD = "ENTER_SEARCH_FIELD";
